"""Rename installer switch colum names

Revision ID: 294fa8c8c153
Revises: ba3c6bdf3b09
Create Date: 2023-07-03 21:53:55.489474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294fa8c8c153'
down_revision = 'ba3c6bdf3b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installer_switch', schema=None) as batch_op:
        batch_op.alter_column('switch_key', new_column_name='parameter')
        batch_op.alter_column('switch_value', new_column_name='value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installer_switch', schema=None) as batch_op:
        batch_op.alter_column('value', new_column_name='switch_value')
        batch_op.alter_column('parameter', new_column_name='switch_key')

    # ### end Alembic commands ###
