"""Allow external installer

Revision ID: 3b9775bd5653
Revises: e28efaaea362
Create Date: 2023-10-30 10:32:50.381868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9775bd5653'
down_revision = 'e28efaaea362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_url', sa.String(length=255), nullable=True))
        # Make column file_name nullable
        batch_op.alter_column('file_name', nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installer', schema=None) as batch_op:
        batch_op.drop_column('external_url')
        # Make column file_name non-nullable
        batch_op.alter_column('file_name', nullable=False)

    # ### end Alembic commands ###
