"""Change name to username in user table

Revision ID: 50b652194afc
Revises: 3d1965dfdcd5
Create Date: 2023-07-01 12:39:22.084231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b652194afc'
down_revision = '3d1965dfdcd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name', new_column_name='username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username', new_column_name='name')


    # ### end Alembic commands ###
