"""Add ResourceType enum

Revision ID: 5c1549a61275
Revises: c993182bb5ec
Create Date: 2024-04-24 14:37:06.525171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1549a61275'
down_revision = 'c993182bb5ec'
branch_labels = None
depends_on = None

resourcetype_enum = sa.Enum('PACKAGE', 'VERSION', 'INSTALLER', 'INSTALLER_SWITCH', 'USER', 'ROLE', 'PERMISSION', name='resourcetype', create_type=True)


def upgrade():
    resourcetype_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_type', resourcetype_enum, nullable=True))

    with op.batch_alter_table('roles_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_id', sa.String(50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles_permissions', schema=None) as batch_op:
        batch_op.drop_column('resource_id')

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_column('resource_type')

    # ### end Alembic commands ###
    # Drop the enum type
    resourcetype_enum.drop(op.get_bind(), checkfirst=True)
