"""Add package enums

Revision ID: 7a37d2375287
Revises: 056faacf0907
Create Date: 2024-04-23 21:51:30.707893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a37d2375287'
down_revision = '056faacf0907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.alter_column('resource_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PACKAGE', 'VERSION', 'INSTALLER', 'INSTALLER_SWITCH', 'SETTING', 'USER', 'ROLE', 'LOG', name='resourcetype'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.alter_column('resource_type',
               existing_type=sa.Enum('PACKAGE', 'VERSION', 'INSTALLER', 'INSTALLER_SWITCH', 'SETTING', 'USER', 'ROLE', 'LOG', name='resourcetype'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)

    # ### end Alembic commands ###
