"""Add settings table

Revision ID: b0f955e346fe
Revises: 3b9775bd5653
Create Date: 2024-02-27 09:21:31.115855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f955e346fe'
down_revision = '3b9775bd5653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('string', 'integer', 'boolean', 'float', 'json'), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('depends_on', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['depends_on'], ['setting.key'], name=op.f('fk_setting_depends_on_setting')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_setting')),
    sa.UniqueConstraint('key', name=op.f('uq_setting_key')),
    sa.UniqueConstraint('name', name=op.f('uq_setting_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
