"""Make fields unique

Revision ID: ba3c6bdf3b09
Revises: 50b652194afc
Create Date: 2023-07-02 12:20:51.560364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3c6bdf3b09'
down_revision = '50b652194afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_package_identifier'), ['identifier'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_package_identifier'), type_='unique')

    # ### end Alembic commands ###
