"""Add Log Tables

Revision ID: c993182bb5ec
Revises: 7d373660d724
Create Date: 2024-04-13 19:56:08.442496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c993182bb5ec'
down_revision = '7d373660d724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log'))
    )
    op.create_table('access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['log.id'], name=op.f('fk_access_log_id_log')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_access_log_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_log'))
    )
    op.create_table('download_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['log.id'], name=op.f('fk_download_log_id_log')),
    sa.ForeignKeyConstraint(['installer_id'], ['installer.id'], name=op.f('fk_download_log_installer_id_installer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_download_log'))
    )
    # ### end Alembic commands ###


def downgrade():
    # Drop tables in reverse order of creation to respect foreign key constraints
    op.drop_table('download_log')  # Depends on 'log'
    op.drop_table('access_log')    # Depends on 'log' and 'user'
    op.drop_table('log')           # Independent, no FK dependencies on this table

