"""Add nested installer columns

Revision ID: e28efaaea362
Revises: 9b131b465fca
Create Date: 2023-07-10 20:51:34.522099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28efaaea362'
down_revision = '9b131b465fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nested_installer_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('installer_id', sa.Integer(), nullable=True),
    sa.Column('relative_file_path', sa.String(length=255), nullable=True),
    sa.Column('portable_command_alias', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['installer_id'], ['installer.id'], name=op.f('fk_nested_installer_file_installer_id_installer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nested_installer_file'))
    )
    with op.batch_alter_table('installer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nested_installer_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installer', schema=None) as batch_op:
        batch_op.drop_column('nested_installer_type')

    op.drop_table('nested_installer_file')
    # ### end Alembic commands ###
